# Generated by Django 4.2.7 on 2025-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_app', models.CharField(max_length=255)),
                ('typing_speed', models.IntegerField(default=0)),
                ('app_switch_count', models.IntegerField(default=0)),
                ('dopamine_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Focused', 'Focused'), ('Distracted', 'Distracted'), ('Doomscrolling', 'Doomscrolling'), ('Neutral', 'Neutral')], max_length=20)),
            ],
        ),
    ]
