# Generated by Django 4.2.7 on 2025-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='status',
            field=models.CharField(choices=[('Focused', 'Focused'), ('Distracted', 'Distracted'), ('Doomscrolling', 'Doomscrolling'), ('Neutral', 'Neutral')], default='Neutral', max_length=20),
        ),
    ]
