# Generated by Django 4.2.7 on 2026-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_useractivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='status',
            field=models.CharField(choices=[('Focused', 'Focused'), ('Distracted', 'Distracted'), ('Doomscrolling', 'Doomscrolling'), ('Neutral', 'Neutral'), ('High Dopamine Risk', 'High Dopamine Risk'), ('Deep Focus Session', 'Deep Focus Session'), ('DOPAMINE SPIKE DETECTED', 'DOPAMINE SPIKE DETECTED')], default='Neutral', max_length=100),
        ),
    ]
