# Generated by Django 4.2.7 on 2026-03-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_useractivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='active_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='scroll_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
